### PR TITLE
Fix issue with Locking

### PR DESCRIPTION
**Pull request by shortnd**
Was using the package along with another that needed access to the request form data and was getting an error that the request was being locked, and wouldn't be able to complete the request because of this.

Made changes where it will now clone the request and do the parsing on that request instead of the actual request to then forward it onto other packages.

### CODE REVIEW

**Comment by rileytomasek** [comment]
Thanks for catching this, @shortnd. The clone is definitely needed for reading `FormData`, but the params parsing only reads `Request.url`. Did you confirm the clone is required for that?

**Comment by mdoury** [comment]
It shouldn't be necessary when accessing `Request.url`. Cloning is only required when calling the request body functions (i.e. `Request.json()`, `Request.text()`, `Request.formData()`, `Request.blob()`, or `Request.arrayBuffer()`) which can only be called once.

https://developer.mozilla.org/en-US/docs/Web/API/Request#instance_methods
> Note: The request body functions can be run only once; subsequent calls will resolve with empty strings/ArrayBuffers.

**Comment by rileytomasek** [comment]
Great. Can you remove the unrelated import changes, then it will be good to merge.

**Comment by shortnd** [comment]
@rileytomasek I removed the import changes. (forgot about auto formatting in editor)

**Pull request merged**
