### PR TITLE
feat: Support FormData object entries parsing

### LINKED ISSUE #14: Unable to parse file uploads handled with `unstable_createFileUploadHandler`
I'm trying to make file uploads type safe using `zx.parseFormSafe` but I'm not able to parse the `NodeOnDiskFile` class.

```typescript
import type { ActionArgs } from "@remix-run/node";
import {
  json,
  NodeOnDiskFile,
  unstable_composeUploadHandlers,
  unstable_createFileUploadHandler,
  unstable_createMemoryUploadHandler,
  unstable_parseMultipartFormData,
} from "@remix-run/node";
import type { ZodError } from "zod";
import { z } from "zod";
import { zx } from "zodix";

function errorAtPath(error: ZodError, path: string) {
  return error.issues.find((issue) => issue.path[0] === path)?.message;
}

export async function action({ request }: ActionArgs) {
  const uploadHandler = unstable_composeUploadHandlers(
    unstable_createFileUploadHandler({
      maxPartSize: 5_000_000,
      file: ({ filename }) => filename,
    }),
    // parse everything else into memory
    unstable_createMemoryUploadHandler()
  );
  const formData = await unstable_parseMultipartFormData(
    request,
    uploadHandler
  );

  const results = await zx.parseFormSafe(formData, {
    file: z.instanceof(NodeOnDiskFile),
    // And some more fields that work just fine 👌
  });

  if (results.success) {
    return await doSomethingWithImage(results.data);
  } else {
    return json({
      success: results.success,
      error: errorAtPath(results.error, "image"),
    });
  }
}
```

`formData.get("image") instanceof NodeOnDiskFile` actually evaluates to `true`.

I found a rather similar [issue](https://github.com/colinhacks/zod/issues/387) on the `zod` repo where running `z.instanceof(File)` on the server resulted in a `Reference Error` because the `File` class is not defined in Node, which is not the case of `NodeOnDiskFile`.

I tried another method to parse the data which would result in an any type inference but would at least throw for missing data :

```typescript
const results = await zx.parseFormSafe(formData, {
    image: z.any().refine((file: unknown) => {
      console.log({ file }); 
      return Boolean(file);
    }, "Image is required."),
  });
```

Which logged `{ file: '[object File]' }` suggesting the file is casted to a string before it reaches the refinement function.

I don't know if this issue comes from `zod` or from `zodix` but maybe someone encountered the issue before and found a workaround. 

Thanks!

### PR DESCRIPTION
**Pull request by mdoury**
Here is a solution to support object entries in `FormData` which enables `<input type="file" />` parsing.

`FormData` object entries are stringified before `FormData` is parsed using the `URLSearchParams` trick.

`FormData` object entries are not parsed by the default parser, making it rather versatile as it enables users to parse object entries of any type using a custom parser. 

I had to make some typings generic in order to support custom parsed search params types.

Fixes #14.

### CODE REVIEW

**Comment by mdoury** [comment]
Thank you, that'd be great!

**Comment by rileytomasek** [comment]
Thanks again for adding this, @mdoury. I just published it as `v0.3.1`.

**Comment by mdoury** [comment]
You're welcome @rileytomasek. I'd be happy to help more if you want.

**Comment by rileytomasek** [comment]
Thanks @mdoury. Let me know if you have any ideas, but I'd like to keep Zodix as lean as possible, and prevent it from evolving into another of the many bloated form libraries.

**Pull request merged**
